"Filed out from Dolphin Smalltalk 7"!

LectorOffice subclass: #LectorExcel
	instanceVariableNames: 'excelReport'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
LectorExcel guid: (GUID fromString: '{f7a9bcde-0c1b-4362-8ed6-00ea5134f6a6}')!
LectorExcel comment: ''!
!LectorExcel categoriesForClass!Unclassified! !
!LectorExcel methodsFor!

free

	^excelReport free! !
!LectorExcel categoriesFor: #free!public! !

