"Filed out from Dolphin Smalltalk 7"!

Office_IMsoDispObj subclass: #OfficeDocumentLibraryVersions
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'OfficeConstants'
	classInstanceVariableNames: ''!
OfficeDocumentLibraryVersions guid: (IID fromString: '{000C0388-0000-0000-C000-000000000046}')!
OfficeDocumentLibraryVersions comment: ''!
!OfficeDocumentLibraryVersions categoriesForClass!COM-Interfaces!Office-Interfaces! !
