"Filed out from Dolphin Smalltalk 7"!

Office_IMsoDispObj subclass: #OfficeCanvasShapes
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'OfficeConstants'
	classInstanceVariableNames: ''!
OfficeCanvasShapes guid: (IID fromString: '{000C0371-0000-0000-C000-000000000046}')!
OfficeCanvasShapes comment: ''!
!OfficeCanvasShapes categoriesForClass!COM-Interfaces!Office-Interfaces! !
