"Filed out from Dolphin Smalltalk 7"!

Office_IMsoDispObj subclass: #OfficeSoftEdgeFormat
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'OfficeConstants'
	classInstanceVariableNames: ''!
OfficeSoftEdgeFormat guid: (IID fromString: '{000C03BC-0000-0000-C000-000000000046}')!
OfficeSoftEdgeFormat comment: ''!
!OfficeSoftEdgeFormat categoriesForClass!COM-Interfaces!Office-Interfaces! !
