"Filed out from Dolphin Smalltalk 7"!

Office_IMsoDispObj subclass: #OfficeAnswerWizard
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'OfficeConstants'
	classInstanceVariableNames: ''!
OfficeAnswerWizard guid: (IID fromString: '{000C0360-0000-0000-C000-000000000046}')!
OfficeAnswerWizard comment: ''!
!OfficeAnswerWizard categoriesForClass!COM-Interfaces!Office-Interfaces! !
