"Filed out from Dolphin Smalltalk 7"!

Office_IMsoDispObj subclass: #OfficeWebPageFonts
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'OfficeConstants'
	classInstanceVariableNames: ''!
OfficeWebPageFonts guid: (IID fromString: '{000C0914-0000-0000-C000-000000000046}')!
OfficeWebPageFonts comment: ''!
!OfficeWebPageFonts categoriesForClass!COM-Interfaces!Office-Interfaces! !
