"Filed out from Dolphin Smalltalk 7"!

Office_IMsoDispObj subclass: #OfficeMetaProperties
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'OfficeConstants'
	classInstanceVariableNames: ''!
OfficeMetaProperties guid: (IID fromString: '{000C038E-0000-0000-C000-000000000046}')!
OfficeMetaProperties comment: ''!
!OfficeMetaProperties categoriesForClass!COM-Interfaces!Office-Interfaces! !
