"Filed out from Dolphin Smalltalk 7"!

Role subclass: #WebUserRole
	instanceVariableNames: 'username password'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
WebUserRole guid: (GUID fromString: '{28b5e0f2-01ee-4d8f-9e64-262522abda3f}')!
WebUserRole comment: ''!
!WebUserRole categoriesForClass!Unclassified! !
!WebUserRole methodsFor!

printString
	^'aWebUserRole ', self name! !
!WebUserRole categoriesFor: #printString!private! !

