"Filed out from Dolphin Smalltalk 7"!

Object subclass: #BBMigrationObject
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
BBMigrationObject guid: (GUID fromString: '{c62205cc-dee5-41cb-99cb-99e43f9d65cd}')!
BBMigrationObject comment: ''!
!BBMigrationObject categoriesForClass!Unclassified! !
!BBMigrationObject class methodsFor!

new

	^super new initialize! !
!BBMigrationObject class categoriesFor: #new!public! !

