"Filed out from Dolphin Smalltalk 7"!

Object subclass: #DataBaseObject
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DataBaseObject guid: (GUID fromString: '{6767e6b9-0dde-4e4e-b356-1dccb76d6cf4}')!
DataBaseObject comment: ''!
!DataBaseObject categoriesForClass!Unclassified! !
!DataBaseObject methodsFor!

isDBTable

	^false! !
!DataBaseObject categoriesFor: #isDBTable!public! !

!DataBaseObject class methodsFor!

new

	^super new initialize! !
!DataBaseObject class categoriesFor: #new!public! !

