"Filed out from Dolphin Smalltalk 7"!

BBMigrationObject subclass: #DBMigrationRule
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DBMigrationRule guid: (GUID fromString: '{9dfb2632-4571-4380-ae6e-d59807220eee}')!
DBMigrationRule comment: ''!
!DBMigrationRule categoriesForClass!Unclassified! !
!DBMigrationRule class methodsFor!

icon

	^Icon fromId: 'LintRule.ico'! !
!DBMigrationRule class categoriesFor: #icon!public! !

