"Filed out from Dolphin Smalltalk 7"!

UMLRelation subclass: #UMLComposition
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLComposition guid: (GUID fromString: '{b430d54b-8202-4b3f-bc9a-09f8893699f7}')!
UMLComposition comment: ''!
!UMLComposition categoriesForClass!Unclassified! !
!UMLComposition methodsFor!

printTypeName

	^'Generalization'! !
!UMLComposition categoriesFor: #printTypeName!public! !

!UMLComposition class methodsFor!

printName

	^'Composition'! !
!UMLComposition class categoriesFor: #printName!public! !

