"Filed out from Dolphin Smalltalk 7"!

UMLGUICategory subclass: #UMLGUIButtomCollectionCategory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLGUIButtomCollectionCategory guid: (GUID fromString: '{9a5c8335-4438-4d6b-9e6f-e596110d76e4}')!
UMLGUIButtomCollectionCategory comment: ''!
!UMLGUIButtomCollectionCategory categoriesForClass!Unclassified! !
!UMLGUIButtomCollectionCategory methodsFor!

isCommandCategory

	^true!

isCommandCollection

	^true! !
!UMLGUIButtomCollectionCategory categoriesFor: #isCommandCategory!public! !
!UMLGUIButtomCollectionCategory categoriesFor: #isCommandCollection!public! !

!UMLGUIButtomCollectionCategory class methodsFor!

defaultName

	^'GUI - Commad Collection'!

icon

	^Icon fromFile: 'icons/Command Collection3.ico'! !
!UMLGUIButtomCollectionCategory class categoriesFor: #defaultName!public! !
!UMLGUIButtomCollectionCategory class categoriesFor: #icon!public! !

