"Filed out from Dolphin Smalltalk 7"!

UMLGUICategory subclass: #UMLGUIValueCategory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLGUIValueCategory guid: (GUID fromString: '{7e674b76-437f-446a-aeca-cece14cc5a7b}')!
UMLGUIValueCategory comment: ''!
!UMLGUIValueCategory categoriesForClass!Unclassified! !
!UMLGUIValueCategory methodsFor!

isValueCategory

	^true! !
!UMLGUIValueCategory categoriesFor: #isValueCategory!public! !

!UMLGUIValueCategory class methodsFor!

defaultName

	^'GUI - Value'!

icon

	^Icon fromId: 'Number.ico'! !
!UMLGUIValueCategory class categoriesFor: #defaultName!public! !
!UMLGUIValueCategory class categoriesFor: #icon!public! !

