"Filed out from Dolphin Smalltalk 7"!

UMLGUICategory subclass: #UMLGUIButtomCollectionUserCategory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLGUIButtomCollectionUserCategory guid: (GUID fromString: '{7d240bc0-a151-4437-934b-1729469c3fdd}')!
UMLGUIButtomCollectionUserCategory comment: ''!
!UMLGUIButtomCollectionUserCategory categoriesForClass!Unclassified! !
!UMLGUIButtomCollectionUserCategory methodsFor!

isCommandCategory

	^true!

isCommandCollection

	^true!

isUserAndCollectionCategory

	^true! !
!UMLGUIButtomCollectionUserCategory categoriesFor: #isCommandCategory!public! !
!UMLGUIButtomCollectionUserCategory categoriesFor: #isCommandCollection!public! !
!UMLGUIButtomCollectionUserCategory categoriesFor: #isUserAndCollectionCategory!public! !

!UMLGUIButtomCollectionUserCategory class methodsFor!

defaultName

	^'GUI - Commad User & Collection'!

icon

	^Icon fromFile: 'U-Fabrik/icons/Command Collection with user.ico'! !
!UMLGUIButtomCollectionUserCategory class categoriesFor: #defaultName!public! !
!UMLGUIButtomCollectionUserCategory class categoriesFor: #icon!public! !

