"Filed out from Dolphin Smalltalk 7"!

UMLGUICategory subclass: #UMLGUIButtomArgCategory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLGUIButtomArgCategory guid: (GUID fromString: '{9f1627d6-c778-43cb-ad5a-0dd751cb4f3a}')!
UMLGUIButtomArgCategory comment: ''!
!UMLGUIButtomArgCategory categoriesForClass!Unclassified! !
!UMLGUIButtomArgCategory methodsFor!

hasArguments

	^true!

isCommandCategory

	^true! !
!UMLGUIButtomArgCategory categoriesFor: #hasArguments!public! !
!UMLGUIButtomArgCategory categoriesFor: #isCommandCategory!public! !

!UMLGUIButtomArgCategory class methodsFor!

defaultName

	^'GUI - Command Arg'!

icon

	^Icon fromFile: 'icons/Command Store Args.ico'! !
!UMLGUIButtomArgCategory class categoriesFor: #defaultName!public! !
!UMLGUIButtomArgCategory class categoriesFor: #icon!public! !

