"Filed out from Dolphin Smalltalk 7"!

UMLGUICategory subclass: #UMLGUICollectionCategory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLGUICollectionCategory guid: (GUID fromString: '{90325a4c-6a7f-478b-bc80-60e43105570d}')!
UMLGUICollectionCategory comment: ''!
!UMLGUICollectionCategory categoriesForClass!Unclassified! !
!UMLGUICollectionCategory methodsFor!

isCollectionCategory

	^true! !
!UMLGUICollectionCategory categoriesFor: #isCollectionCategory!public! !

!UMLGUICollectionCategory class methodsFor!

defaultName

	^'GUI - Collection Tabs'!

icon

	^Icon fromFile: 'icons/tabs.ico'! !
!UMLGUICollectionCategory class categoriesFor: #defaultName!public! !
!UMLGUICollectionCategory class categoriesFor: #icon!public! !

