"Filed out from Dolphin Smalltalk 7"!

UMLComponentAgrupationDescriptor subclass: #UMLObjectGroupViewDescriptor
	instanceVariableNames: 'groupName'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLObjectGroupViewDescriptor guid: (GUID fromString: '{42fab06e-3108-4201-a5d1-5c5466d92bd9}')!
UMLObjectGroupViewDescriptor comment: ''!
!UMLObjectGroupViewDescriptor categoriesForClass!Unclassified! !
!UMLObjectGroupViewDescriptor methodsFor!

initialize

	super initialize.

	groupName := ''.! !
!UMLObjectGroupViewDescriptor categoriesFor: #initialize!public! !

!UMLObjectGroupViewDescriptor class methodsFor!

icon

	^Icon fromId: 'GroupBox.ico'! !
!UMLObjectGroupViewDescriptor class categoriesFor: #icon!public! !

