"Filed out from Dolphin Smalltalk 7"!

UMLRelationAbstractDifference subclass: #UMLSuperclassDifference
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLSuperclassDifference guid: (GUID fromString: '{e1f7254b-eed6-4898-a183-362c707141ec}')!
UMLSuperclassDifference comment: ''!
!UMLSuperclassDifference categoriesForClass!Unclassified! !
!UMLSuperclassDifference methodsFor!

typeString

	^'Navigability Superclass Change'! !
!UMLSuperclassDifference categoriesFor: #typeString!public! !

!UMLSuperclassDifference class methodsFor!

isComboSelectable

	^true!

printComboName

	^'Superclass changed'! !
!UMLSuperclassDifference class categoriesFor: #isComboSelectable!public! !
!UMLSuperclassDifference class categoriesFor: #printComboName!public! !

