"Filed out from Dolphin Smalltalk 7"!

UMLObject subclass: #UMLSanityCheck
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UMLSanityCheck guid: (GUID fromString: '{84b45cbc-a3e7-4280-83a0-6bd641d9ef68}')!
UMLSanityCheck comment: ''!
!UMLSanityCheck categoriesForClass!Unclassified! !
!UMLSanityCheck methodsFor!

hasNode

	^false! !
!UMLSanityCheck categoriesFor: #hasNode!public! !

